[package]
name = "ferris-twitch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
colored = "2.1.0"
dotenv = { version = "0.15.0", features = ["cli", "clap"] }
futures-util = "0.3.30"
hex-rgb = "0.1.1"
image = "0.24.8"
irc = "0.15.0"
openssl = "0.10.63"
reqwest = { version = "0.11.24", features = ["blocking", "rustls"] }
tokio = { version = "1.36.0", features = ["full"] }
